// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetCurrentState(ctx context.Context, state StateToTrack) (CurrentState, error)
	GetLatestBlockNumber(ctx context.Context) (interface{}, error)
	InsertPixelMapTransaction(ctx context.Context, arg InsertPixelMapTransactionParams) (int32, error)
	UpdateCurrentState(ctx context.Context, arg UpdateCurrentStateParams) error
}

var _ Querier = (*Queries)(nil)
