# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image: 389059433654.dkr.ecr.us-east-1.amazonaws.com/backend:1.0
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
